# Generated by Django 5.2.13 on 2026-04-29 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('connect', 'Account connected'), ('disconnect', 'Account disconnected'), ('sync', 'Sync'), ('ai', 'AI request'), ('export', 'Export'), ('2fa', '2FA change'), ('share', 'Share toggle'), ('settings', 'Settings change'), ('other', 'Other')], db_index=True, default='other', max_length=24)),
                ('message', models.CharField(max_length=400)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_activi_user_id_33cb61_idx')],
            },
        ),
    ]
