# Generated by Django 5.2.13 on 2026-04-19 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], db_index=True, max_length=16)),
                ('score', models.FloatField(help_text='Confidence score, 0..1')),
                ('model_name', models.CharField(default='vader', max_length=64)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='collectors.comment')),
            ],
            options={
                'indexes': [models.Index(fields=['label'], name='analytics_s_label_f5602b_idx')],
            },
        ),
    ]
