"""Smoke tests for the dashboard page surface.

Covers all the new pages added in the T1–T3 batch (post generator,
best-time, hashtags, 2FA, activity, plus the saved-views API). Goal is
to catch obvious 500s — they all should return 200 (or 302 to login)
for a fresh authenticated user, even when there is no data.

These tests intentionally don't assert on body content; they exist to
keep the URL/view wiring honest as the codebase grows.
"""
from __future__ import annotations

import pytest
from django.contrib.auth import get_user_model
from django.test import Client
from django.urls import reverse

pytestmark = pytest.mark.django_db


@pytest.fixture
def user():
    """Fresh user with a working password — no demo data, so each page
    has to render its empty state cleanly."""
    User = get_user_model()
    u = User(username="smoke@example.com", email="smoke@example.com")
    u.set_password("x!23QWE-pass")
    u.save()
    return u


@pytest.fixture
def client(user):
    c = Client()
    c.force_login(user)
    return c


# ---------- Login-required pages — should all 200 ----------

@pytest.mark.parametrize("urlname", [
    "dashboard:app",
    "social:accounts",
    "analytics:overview",
    "analytics:sentiment",
    "analytics:top_posts",
    "analytics:compare",
    "analytics:chat",
    "analytics:digest",
    "analytics:alerts",
    "analytics:best_time",
    "accounts:settings",
    "accounts:two_factor",
    "accounts:activity",
])
def test_dashboard_pages_render(client, urlname):
    """Every dashboard URL returns 200 for a logged-in user with no data."""
    url = reverse(urlname)
    resp = client.get(url)
    assert resp.status_code == 200, f"{urlname} returned {resp.status_code}"


# ---------- Anonymous → redirected to login ----------

@pytest.mark.parametrize("urlname", [
    "dashboard:app",
    "analytics:chat",
    "analytics:best_time",
    "accounts:two_factor",
])
def test_dashboard_pages_require_login(urlname):
    """Anonymous visits get bounced to login (302)."""
    c = Client()
    resp = c.get(reverse(urlname))
    assert resp.status_code in (302, 301), f"{urlname} did not redirect"


# ---------- Saved views CRUD ----------

def test_saved_views_create_list_delete(client):
    url = reverse("analytics:saved_views")

    # List → empty
    resp = client.get(url + "?page=top_posts")
    assert resp.status_code == 200
    assert resp.json() == {"views": []}

    # Create
    resp = client.post(url, {"page": "top_posts", "name": "MyFilter", "query": "sort=likes"})
    assert resp.status_code == 200
    body = resp.json()
    assert body["created"] is True
    pk = body["view"]["id"]

    # List → 1 row
    resp = client.get(url + "?page=top_posts")
    assert len(resp.json()["views"]) == 1

    # Delete
    resp = client.delete(url + f"?id={pk}")
    assert resp.status_code == 200

    # Empty again
    resp = client.get(url + "?page=top_posts")
    assert resp.json() == {"views": []}


# ---------- Global search ----------

def test_global_search_short_query_returns_empty(client):
    resp = client.get(reverse("dashboard:search") + "?q=a")
    assert resp.status_code == 200
    assert resp.json() == {"results": []}


def test_global_search_no_data_returns_empty(client):
    resp = client.get(reverse("dashboard:search") + "?q=anything")
    assert resp.status_code == 200
    assert resp.json() == {"results": []}


# ---------- AI insight: no API key → 503 ----------

def test_ai_insight_unconfigured(client, settings):
    settings.OPENAI_API_KEY = ""
    resp = client.post(reverse("analytics:insight"), {"topic": "overview"})
    assert resp.status_code == 503


# ---------- 2FA setup is idempotent on GET ----------

def test_two_factor_setup_creates_secret(client, user):
    """Visiting /2fa/ when no secret exists should generate one."""
    resp = client.get(reverse("accounts:two_factor"))
    assert resp.status_code == 200
    user.refresh_from_db()
    assert user.totp_secret  # got generated
    assert not user.totp_enabled


def test_two_factor_disable(client, user):
    """Disable wipes the secret + flag."""
    user.totp_secret  = "JBSWY3DPEHPK3PXP"
    user.totp_enabled = True
    user.save()

    resp = client.post(reverse("accounts:two_factor"), {"action": "disable"})
    assert resp.status_code == 200
    user.refresh_from_db()
    assert user.totp_enabled is False
    # Empty secret means a fresh one was auto-generated by the view since
    # 2FA is now off — that's expected, not an error.
