# Generated by Django 5.2.13 on 2026-04-19 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('x', 'X (Twitter)')], db_index=True, max_length=16)),
                ('external_id', models.CharField(help_text='Platform-side account id', max_length=128)),
                ('handle', models.CharField(help_text='Public @username or channel id', max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=256)),
                ('avatar_url', models.URLField(blank=True)),
                ('follower_count', models.PositiveIntegerField(default=0)),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='True for accounts seeded by the demo generator.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=128)),
                ('post_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('reel', 'Reel'), ('carousel', 'Carousel'), ('tweet', 'Tweet'), ('channel_post', 'Channel post')], default='photo', max_length=16)),
                ('caption', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0, help_text='(likes + comments + shares) / views')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social.connectedaccount')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.AddIndex(
            model_name='connectedaccount',
            index=models.Index(fields=['user', 'platform'], name='social_conn_user_id_54e402_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='connectedaccount',
            unique_together={('platform', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['account', '-published_at'], name='social_post_account_f8ba95_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-published_at'], name='social_post_publish_3ba08d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('account', 'external_id')},
        ),
    ]
