# Generated by Django 5.2.13 on 2026-04-24 12:31

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_publicsharelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedaccount',
            name='access_token',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='connectedaccount',
            name='refresh_token',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='connectedaccount',
            name='scopes',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='connectedaccount',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
