# Generated by Django 5.2.13 on 2026-04-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_connectedaccount_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedaccount',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('x', 'X (Twitter)'), ('vk', 'VKontakte')], db_index=True, max_length=16),
        ),
    ]
