# Generated by Django 5.2.13 on 2026-04-28 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_connectedaccount_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField()),
                ('recorded_on', models.DateField(db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_snapshots', to='social.connectedaccount')),
            ],
            options={
                'ordering': ['-recorded_on'],
                'indexes': [models.Index(fields=['account', '-recorded_on'], name='social_foll_account_3dbc3f_idx')],
                'unique_together': {('account', 'recorded_on')},
            },
        ),
    ]
