# Generated by Django 5.2.13 on 2026-04-28 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_followersnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('x', 'X (Twitter)'), ('vk', 'VKontakte')], db_index=True, max_length=16)),
                ('handle', models.CharField(help_text='Public @username yoki kanal id', max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=256)),
                ('follower_count', models.PositiveIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, help_text='Eslatma — nima uchun kuzatasiz', max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-follower_count'],
                'unique_together': {('user', 'platform', 'handle')},
            },
        ),
    ]
